apiVersion: v1
kind: Service
metadata:
  name: @name-service
  namespace: @_namespace
spec: 
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app: @name
